### PR TITLE
Add ccr instructions

### PR DESCRIPTION
**Pull request by raakal**
This will add a new subsection to the Participation Certificate letting McGill student users know about the CCR option for their transcript. It includes a heading, an introduction with information about CCR and 3 steps to validate their hours for recognition.

The french keys are not yet translated and will need to be updated.

### CODE REVIEW

**Comment by rsmithlal** [comment]
@raakal, what's the status on this pull request? Are you ready for it to be reviewed and then deployed?

**Comment by raakal** [comment]
Hi @rsmithlal , its deployable except for the fact that we don't have the french translations. Would you suggest deploying anyways and updating the French after the fact?

**Comment by rsmithlal** [comment]
Yes, that would be fine. We can add the French translations whenever they are ready!  ---- On Sat, 02 Jan 2021 17:08:50 -0330  notifications@github.com  wrote ----
Hi @rsmithlal , its deployable except for the fact that we don't have the french translations. Would you suggest deploying anyways and updating the French after the fact?

**Review by rsmithlal — APPROVED** [review]
Everything looks great here!

I adjusted some of the positioning of some other page elements and added more structure to the page as a whole.

Great job!

**Pull request merged**
